AWSTemplateFormatVersion: '2010-09-09'

Description: RDS template with YAML - RDS Definition Depends on 1-vpc-cfn.yml, 2-sg-cfn.yml

Parameters:
  VPCName:
    Description: Target VPC Stack Name
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: debugroom-sample-aws-xray-vpc
  RDSUserName:
    Description: RDS User Name for Master
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: postgres

Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    UpdateReplacePolicy: Snapshot
    DeletionPolicy: Snapshot
    Properties:
      DBInstanceIdentifier: debugroom-sample-aws-xray-rds
      DBName: sample_database
      Engine: postgres
      MultiAZ: false
      MasterUsername: !Ref RDSUserName
      MasterUserPassword: '{{resolve:ssm-secure:sample-xray-rds-master-password:1}}'
      DBInstanceClass: db.m5.large
      AllocatedStorage: '20'
      DBSubnetGroupName: !Ref DBSubnetGroup
      MonitoringInterval: 10
      MonitoringRoleArn: !GetAtt DBMonitorRole.Arn
      PubliclyAccessible: true
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub ${VPCName}-SecurityGroupRdsPostgres

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DB Subnet Group for Private Subnet
      SubnetIds:
        - Fn::ImportValue: !Sub ${VPCName}-PublicSubnet1
        - Fn::ImportValue: !Sub ${VPCName}-PublicSubnet2

  DBMonitorRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - monitoring.rds.amazonaws.com
            Action:
              - sts:AssumeRole

Outputs:
  RDSDBNAME:
    Description: DB Name for RDS
    Value: !Ref RDSInstance
    Export:
      Name: !Sub ${VPCName}-RDS-DBName

  RDSProductionInstanceEndPoint:
    Description: RDS Endpoint
    Value: !GetAtt RDSInstance.Endpoint.Address
    Export:
      Name: !Sub ${VPCName}-RDS-Endpoint

  RDSUserName:
    Description: DB User Name for Master
    Value: !Ref RDSUserName
    Export:
      Name: !Sub ${VPCName}-RDS-UserName