AWSTemplateFormatVersion: '2010-09-09'

Description: CloudFormation template with YAML - ALB Target group.  Depends On 1-vpc-cfn.yml, 2-sg-cfn.yml, 3-frontend-alb-cfn.yml.

Mappings:
  DeployEnvironmentMap:
    Production:
      "Protocol": "HTTPS"
      "Port": 443
    Staging:
      "Protocol": "HTTP"
      "Port": 80
    Dev:
      "Protocol": "HTTP"
      "Port": 80

Parameters:
  VPCName:
    Description: Target VPC Name
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: debugroom-sample-aws-xray-vpc
  EnvType:
    Description: Which environments to deploy your service.
    Type: String
    AllowedValues: ["Dev", "Staging", "Production"]
    Default: Dev

Resources:
  FrontendAppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub FrontendApp-tg-${EnvType}
      VpcId:
        Fn::ImportValue: !Sub ${VPCName}-VPCID
      Port: !FindInMap [DeployEnvironmentMap, !Ref EnvType, Port]
      Protocol: !FindInMap [DeployEnvironmentMap, !Ref EnvType, Protocol]
      HealthCheckPath: /frontend/portal
      HealthCheckIntervalSeconds: 60
      HealthyThresholdCount: 2
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '60'

  FrontendAppListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref FrontendAppTargetGroup
      Conditions:
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - /frontend/*
      ListenerArn:
        Fn::ImportValue: !Sub ${VPCName}-FrontendALB-Listener-${EnvType}
      Priority: 1

Outputs:
  TargetGroup:
    Description: TargetGroup Service
    Value: !Ref FrontendAppTargetGroup
    Export:
      Name: !Sub ${VPCName}-FrontendApp-TargetGroup-${EnvType}